#spring:
#  application:
#  name: config-server
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/config
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest


spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mstf-yalcin/config.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include:
            - rabbit




server:
  port: 8071