# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: notification-service-deployment
serviceName: notification-service
appLabel: notification-service
appName: notification-service

replicaCount: 1

image:
  repository: notification-service
  tag: v1.0

containerPort: 9010

service:
  type: ClusterIP
  port: 9010
  targetPort: 9010

appname_enabled: true
profile_enabled: false
config_enabled: false
discovery_enabled: false
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: true

