services:

  config-server:
    image: config-server:v1
    ports:
      - "8071:8071"
    environment:
      SPRING_APPLICATION_NAME: config-server
    extends:
      file: common-config.yml
      service: microservice-base-config
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  eureka-server:
    image: eureka-server:v1
    container_name: eureka-server-ms
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-config-server-config
    environment:
      SPRING_APPLICATION_NAME: eureka-server


  accounts:
    image: accounts:v1
    container_name: accounts-ms
    ports:
      - "8080:8080"
    extends:
      file: common-config.yml
      service: microservice-eureka-config
    environment:
      SPRING_APPLICATION_NAME: accounts
    depends_on:
      config-server:
        condition: service_healthy


  loans:
    image: loans:v1
    ports:
      - "8090:8090"
    extends:
      file: common-config.yml
      service: microservice-eureka-config
    environment:
      SPRING_APPLICATION_NAME: loans
    depends_on:
      config-server:
        condition: service_healthy

  cards:
    image: cards:v1
    ports:
    - "9000:9000"
    extends:
      file: common-config.yml
      service: microservice-eureka-config
    environment:
      SPRING_APPLICATION_NAME: cards
    depends_on:
      config-server:
        condition: service_healthy

networks:
  test-network:
    driver: bridge